# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40e512689013204e28e72ad8b6901f959e257ce70397b60ea65e914236bf3e1c583866b7f0765b52b383664f975f0cc2b46fe208aafd587e776f67f602a977a2

test:
  secret_key_base: 2010e0a17a821baa175c3ae24e826bfead4b30df1acd77c6af8c0da17605ab2614fc8347c7ee457f94e038aa7d1b388c9f48683ba4ebeff34c383bf05d443e16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
